create table if not exists leads (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  project_name text not null,
  company text,
  state text,
  source_url text,
  status text default 'New',
  priority text default 'Medium',
  notes text
);

alter table leads enable row level security;

drop policy if exists "Allow public read" on leads;
drop policy if exists "Allow public insert" on leads;
drop policy if exists "Allow public update" on leads;
drop policy if exists "Allow public delete" on leads;

create policy "Allow public read" on leads for select using (true);
create policy "Allow public insert" on leads for insert with check (true);
create policy "Allow public update" on leads for update using (true);
create policy "Allow public delete" on leads for delete using (true);
